# Generated by Django 3.0.6 on 2020-05-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('artist', models.CharField(max_length=20)),
                ('bpm', models.IntegerField()),
                ('is_encore', models.BooleanField(default='False', verbose_name='encore')),
            ],
        ),
    ]
