# Generated by Django 3.0.6 on 2020-05-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_song'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='BandMember',
        ),
        migrations.AlterField(
            model_name='song',
            name='is_encore',
            field=models.BooleanField(default=False, verbose_name='encore'),
        ),
    ]
