# Generated by Django 3.0.6 on 2020-05-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandmember',
            name='band',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generator.Band'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='band',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generator.Band'),
            preserve_default=False,
        ),
    ]
