# Generated by Django 3.0.6 on 2020-05-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20200517_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='key',
            field=models.CharField(default='A', max_length=5),
            preserve_default=False,
        ),
    ]
